// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rabqxejdzrkudkkldvoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhYnF4ZWpkenJrdWRra2xkdm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzQ5MTcsImV4cCI6MjA3MjYxMDkxN30.WWQKVgrPUZ6xorBA7uy1zlKQyG9EYP4E4bGqClHtnDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});