// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwmwbttcsfgtseqzmpwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3bXdidHRjc2ZndHNlcXptcHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODc2MzMsImV4cCI6MjA3MjY2MzYzM30.lk1np8zJsJV3YgreSM8sie53s4jqrej-rDuHwNA4PD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});